# @see https://docs.styleci.io/configuration#default-configuration
preset: laravel


# php:
#   preset: laravel
#   disabled:
#     - no_unused_imports
#   finder:
#     not-name:
#       - index.php
# js:
#   finder:
#     not-name:
#       - vite.config.js
# css: true
